---
engines:
  checkstyle:
    enabled: false
  pmd:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  scss-lint:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.java"
  - "**.js"
  - "**.md"
  - "**.scss"
exclude_paths: []
