language: java
sudo: false
jdk:
    - oraclejdk8
beforeinstall:
    - chmod +x gradlew   
script:
    - ./gradlew clean build
branches:
  only:
    - master
    - develop
    - /^feature.*$/
    - /^hotfix.*$/
notifications:
  email: false
