language: java
sudo: false
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - ./gradlew clean build
branches:
  only:
    - master
    - develop
    - /^feature.*$/
    - /^hotfix.*$/
notifications:
  email: false
