sudo: required
addons:
  code_climate:
    repo_token: cf215ce22e6a57dc1711ee432d5e3526eea94636ea75822810ac9ceab7311f1f
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/
language: java
jdk:
  - oraclejdk8
services:
  - rabbitmq
  - docker
before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - chmod +x gradlew
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
script:
  - ./gradlew clean build
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
branches:
  only:
    - master
    - develop
    - /^feature.*$/
    - /^hotfix.*$/
notifications:
  email: false
env:
  global:
    - GH_REF: github.com/hetzijzo/strucdocs.git
