sudo: required
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/
language: java
jdk:
  - oraclejdk8
services:
  - rabbitmq
  - docker
before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - chmod +x gradlew
script:
  - ./gradlew clean build
branches:
  only:
    - master
    - develop
    - /^feature.*$/
    - /^hotfix.*$/
notifications:
  email: false
env:
  global:
    - GH_REF: github.com/hetzijzo/strucdocs.git
