version: '2'
services:
  eureka:
    container_name: strucdocs-eureka
    build:
      context: ./strucdocs-eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  edge:
    container_name: strucdocs-edge
    build:
      context: ./strucdocs-edge
    ports:
      - "80:80"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    links:
      - eureka
  zipkin:
    container_name: strucdocs-zipkin
    build:
      context: ./strucdocs-zipkin
    ports:
      - "9411:9411"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    links:
      - eureka
  transpose-service:
    container_name: strucdocs-transpose-service
    build:
      context: ./strucdocs-transpose-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    links:
      - eureka
