spring.application.name: transpose-service
info.id: ${spring.application.name}

server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth.sampler.percentage: 10.0

---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80

---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
