spring.application.name: zipkin
info.id: ${spring.application.name}

server.port: ${PORT:9411}

spring:
  datasource.initialize: false
  sleuth.enabled: false
zipkin.store.type: mem

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80

---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
